language: python
sudo: false
python:
  - 3.4
  - 3.5
env:
  global:
    - PYTHONWARNINGS=default,ignore::PendingDeprecationWarning
    - PYTHONASYNCIODEBUG=1
matrix:
  fast_finish: true
install:
  - travis_retry pip install --upgrade pip
  - travis_retry pip install -e .[test]
script:
  - py.test tests --cov=aiohttp_wsgi --cov-report=term-missing
notifications:
  email: false
