language: python
sudo: false
python:
  - 3.3
  - 3.4
matrix:
  fast_finish: true
install:
  - travis_retry pip install -e .[test]
script: 
  - py.test tests --cov=aiohttp_wsgi --cov-report=term-missing
notifications:
  email: false
