language: python
sudo: false
python:
  - 3.5
env:
  matrix:
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=flake8
    - TOXENV=docs
  global:
    - PYTHONWARNINGS=default,ignore::PendingDeprecationWarning
    - PYTHONASYNCIODEBUG=1
matrix:
  fast_finish: true
install:
  - pip install 'tox>=2.3.1'
script: tox
notifications:
  email: false
