dist: trusty
language: python
python:
- 3.6
sudo: false
env:
  global:
  - PYTHONWARNINGS=default,ignore::PendingDeprecationWarning
  - PYTHONASYNCIODEBUG=1
install:
- pyenv install -s 3.6
- pyenv install -s 3.5
- pyenv install -s 3.4
- pyenv install -s 2.7
- pyenv shell 3.6 3.5 3.4 2.7
- pip install 'tox>=2.3.1'
script: tox
notifications:
  email: false
deploy:
  provider: pypi
  user: etianen
  password:
    secure: X9E2HsOMOSmLcH0br9LlNy8EI7AYEf7lGKM2gCOgxWYd7M9i3rL9nPT8JJWzilQgCigjQ3L9q5wTSvp5LxxOVqCQgIUktTKXuIEJgWKcF6kKnq8usFETeXLAIAf4J0BnyGHK7pWTPA0ocZv4wmVfOEVymzwogbWT4uSs1vhFSRQ=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: etianen/aiohttp-wsgi
