dist: trusty
language: python
python:
  - 3.5
sudo: false
env:
  global:
    - PYTHONWARNINGS=default,ignore::PendingDeprecationWarning
    - PYTHONASYNCIODEBUG=1
before_install:
  # Install the latest version of pyenv.
  - rm -rf ~/.pyenv
  - curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash
  # Install python.
  - cat .python-version | xargs -n 1 pyenv install
install:
  - pip install 'tox>=2.3.1'
script: tox
notifications:
  email: false
